version: '3'
services:
  fc-city:
    container_name: fc-city-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
      - "${ADMIN_PORT:-8090}:8090"
    volumes:
      - ./pb_data:/app/pb_data
      - ./pb_migrations:/app/pb_migrations
    environment:
      - PORT=3000
      - ADMIN_PORT=8090
      - SENDGRID_API_KEY=
      - STORE_EMAIL=
      - POCKETBASE_URL=http://localhost:8090