[program:node]
command=node src/server.js
autostart=true
autorestart=true
stderr_logfile=/var/log/node_err.log
stdout_logfile=/var/log/node_out.log

[program:pocketbase]
command=./pocketbase serve
autostart=true
autorestart=true
stderr_logfile=/var/log/pocketbase_err.log
stdout_logfile=/var/log/pocketbase_out.log

